"""empty message

Revision ID: 09f5c38bd37d
Revises: 815e93f7fdc5
Create Date: 2020-04-24 14:55:38.039671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f5c38bd37d'
down_revision = '815e93f7fdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('frequency_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'frequency_days')
    # ### end Alembic commands ###
