"""empty message

Revision ID: 815e93f7fdc5
Revises: 
Create Date: 2020-04-23 11:37:33.983646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815e93f7fdc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=3), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('time_creation', sa.DateTime(), nullable=True),
    sa.Column('time_completion', sa.DateTime(), nullable=True),
    sa.Column('show_timeline', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('id_strategy', sa.Integer(), nullable=False),
    sa.Column('show_timeline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_strategy'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=True),
    sa.Column('time_creation', sa.DateTime(), nullable=True),
    sa.Column('time_completion', sa.DateTime(), nullable=True),
    sa.Column('time_due', sa.DateTime(), nullable=True),
    sa.Column('time_line', sa.String(length=20), nullable=True),
    sa.Column('duration_plan', sa.Interval(), nullable=False),
    sa.Column('duration_real', sa.Interval(), nullable=False),
    sa.Column('timer_start', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('show_menu', sa.Boolean(), nullable=False),
    sa.Column('id_strategy', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['project.id'], ),
    sa.ForeignKeyConstraint(['id_strategy'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('project')
    op.drop_table('strategy')
    # ### end Alembic commands ###
