"""empty message

Revision ID: a104e38a9cf5
Revises: 
Create Date: 2020-04-02 16:36:40.404728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a104e38a9cf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=3), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('time_creation', sa.DateTime(), nullable=True),
    sa.Column('time_completion', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('plan', sa.Interval(), nullable=False),
    sa.Column('actual', sa.Interval(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id_strategy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_strategy'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('strategy')
    op.drop_table('project')
    # ### end Alembic commands ###
